cabal-version:      3.0
name:               kestrel-core
version:            0.0.1.0
synopsis:           Programmable parametric CAD core for Kestrel
build-type:         Simple

library
    hs-source-dirs:     src
    exposed-modules:
        Kestrel.Geometry
        Kestrel.Model
        Kestrel.Units
    build-depends:
        base >=4.17 && <5
    default-language:   Haskell2010
    ghc-options:        -Wall

executable kestrel-model
    hs-source-dirs:     app
    main-is:            Main.hs
    build-depends:
        base >=4.17 && <5,
        kestrel-core
    default-language:   Haskell2010
    ghc-options:        -Wall
